version: 2
updates:
- package-ecosystem: npm
  directory: "/src/wordpress/wp-content/themes/www_perlur_cloud"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - mark-stopka
  labels:
  - javascript
  ignore:
  - dependency-name: npm
    versions:
    - 7.10.0
    - 7.11.0
    - 7.5.3
    - 7.6.0
    - 7.7.5
    - 7.8.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.6
    - 1.4.0
    - 1.5.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: css-loader
    versions:
    - 5.1.0
