on: 
  push:
  pull_request:
    branches:
      - 'master'

name: Test Docker build

jobs:
  frontend-build:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Start Docker environment
        run: |
          ln -s docker-compose.local.yml docker-compose.yml
          docker-compose up -d
      - name: Prepare container (Node.js and NPM)
        run:  |
          docker-compose exec -T web apt-get update
          docker-compose exec -T web apt-get install -y nodejs
      - name: Build assets
        run: |
          docker-compose exec -T web pushd src/wordpress/wp-content/themes/www_perlur_cloud/
          docker-compose exec -T web npm run-script build
          docker-compose exec -T web popd
