on: 
  push:
  pull_request:
    branches:
      - 'master'

name: Test Webpack build

jobs:
  frontend-build:
    name: Build frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Switch directory
        run: pushd src/wordpress/wp-content/themes/www_perlur_cloud/
      - name: Install NPM dependencies
        run: npm install
      - name: Build assets
        run: |
          npm run-script build
          popd
